apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: helloapp
spec:
  type: LoadBalancer
  selector:
    app: helloapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: helloapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: codecatalyst-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: rushidockerhub1881/helloapp:latest
        ports:
        - containerPort: 80
